# Generated by Django 6.0 on 2025-12-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blogs_author_alter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
